# variables are defined in .env file
projects:
  
schema:
  - "https://niantic-social-api.nianticlabs.com/graphql":
      headers:
        Authorization: Bearer ${TOKEN}
  - "https://niantic-social-api.nianticlabs.com/public/graphql":
documents: '**/*.graphql'
