# variables are defined in .env file
schema:
  - "https://niantic-social-api.nianticlabs.com/public/graphql":
  - "https://niantic-social-api.nianticlabs.com/graphql":
      headers:
        Authorization: Bearer ${TOKEN}
documents: '**/*.graphql'

