ALTER TABLE members
    ADD COLUMN username   VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN avatar_url VARCHAR(255) NOT NULL DEFAULT '';

ALTER TABLE events
    ADD COLUMN raw_json JSONB NOT NULL DEFAULT '{}';