ALTER TABLE events
    ADD COLUMN imported_at TIMESTAMP NOT NULL DEFAULT NOW();

ALTER TABLE members
    ADD COLUMN imported_at TIMESTAMP NOT NULL DEFAULT NOW(),
    ADD COLUMN raw_json    JSONB     NOT NULL DEFAULT '{}'::JSONB;

ALTER TABLE clubs
    ADD COLUMN imported_at TIMESTAMP NOT NULL DEFAULT NOW(),
    ADD COLUMN raw_json    JSONB     NOT NULL DEFAULT '{}'::JSONB;

ALTER TABLE event_rsvps
    ADD COLUMN imported_at TIMESTAMP NOT NULL DEFAULT NOW();
